### ISSUE TITLE
When I run 'installer.php', I get the following error:

### ISSUE THREAD

**Issue by brycematheson** [luizbossoi/whm-cpanel-api-wordpress-installation#1]
Error:

Parse error: syntax error, unexpected '==' (T_IS_EQUAL), expecting ')' in /home/shdevvip/public_html/create/classes/WHMcPanelWizard.class.php on line 336

Any ideas what may be causing that?

**Comment by luizbossoi** [comment]
Hello @brycematheson 

This issue is now fixed, the wrong deployment was done here on github.
You can clone the entire repository again and try it out.

I've just added Docker support, to make it easier to deploy

Thanks
